config/routes.rb
# frozen_string_literal: true

require "sidekiq/web"
require "staff_constraint"

Rails.application.routes.draw do
  mount Peek::Railtie => "/peek"

  root to: "pages#home"

  get  "/login",  to: "sessions#new",     as: "login"
  post "/logout", to: "sessions#destroy", as: "logout"

  match "/auth/:provider/callback", to: "sessions#create",  via: %i[get post]
  match "/auth/failure",            to: "sessions#failure", via: %i[get post]

  get "/a/:short_key", to: "short_url#assignment_invitation",       as: "assignment_invitation_short"
  get "/g/:short_key", to: "short_url#group_assignment_invitation", as: "group_assignment_invitation_short"

  get "/autocomplete/github_repos", to: "autocomplete#github_repos"

  get "/boom", to: "site#boom_town"
  get "/boom/sidekiq", to: "site#boom_sidekiq"

  scope "github", as: "github" do
    constraints user_agent: %r{\AGitHub-Hookshot/\w+\z}, format: "json" do
      post :hooks, to: "hooks#receive"
    end
  end

  resources :assignment_invitations, path: "assignment-invitations", only: [:show] do
    member do
      patch :accept
      get   :setup
      patch :setup_progress
      get   :success
      patch :join_roster
    end
  end

  resources :group_assignment_invitations, path: "group-assignment-invitations", only: [:show] do
    member do
      get   :accept
      patch :accept_assignment
      patch :accept_invitation
      get   :setup
      patch :setup_progress
      get   :successful_invitation, path: :success
      patch :join_roster
    end
  end

  scope path_names: { edit: "settings" } do
    resources :organizations, path: "classrooms" do
      member do
        get   :invite
        get   :new_assignment, path: "new-assignment"
        get   :setup
        patch :setup_organization
        get   "settings/invitations", to: "organizations#invitation"
        get   "settings/teams",       to: "organizations#show_groupings"
        delete "users/:user_id",      to: "organizations#remove_user", as: "remove_user"

        resource :roster, only: %i[show new create], controller: "orgs/rosters" do
          patch :link
          patch :unlink
          patch :delete_entry
          patch :add_students
          patch :remove_organization
        end
      end

      resources :groupings, only: %i[show edit update] do
        resources :groups, only: [:show] do
          member do
            patch "/memberships/:user_id", to: "groups#add_membership", as: "add_membership"
            delete "/memberships/:user_id", to: "groups#remove_membership", as: "remove_membership"
          end
        end
      end

      resources :assignments do
        get :desktop, on: :member
        resources :assignment_repos, only: [:show], controller: "orgs/assignment_repos"
        get "/roster_entries/:roster_entry_id", to: "orgs/roster_entries#show", as: "roster_entry"
      end

      resources :group_assignments, path: "group-assignments" do
        resources :group_assignment_repos, only: [:show], controller: "orgs/group_assignment_repos"
        get "/roster_entries/:roster_entry_id", to: "orgs/roster_entries#show", as: "roster_entry"
      end
    end
  end

  resources :videos, only: [:index]

  namespace :stafftools do
    constraints StaffConstraint.new do
      mount Sidekiq::Web => "/sidekiq"
      mount Flipper::UI.app(GitHubClassroom.flipper) => "/flipper", as: "flipper"
    end

    root "resources#index", as: :root
    get "/resource_search", to: "resources#search"

    resources :users, only: [:show] do
      member do
        post :impersonate
        delete :stop_impersonating
      end
    end

    resources :organizations, path: "classrooms", only: [:show] do
      member do
        delete "/users/:user_id", to: "organizations#remove_user", as: "remove_user"
      end
    end

    resources :repo_accesses, only: [:show]

    resources :assignment_invitations, only: [:show]
    resources :assignment_repos,       only: %i[show destroy]
    resources :assignments,            only: [:show]

    resources :deadlines, only: [:show]

    resources :group_assignment_invitations, path: "group-assignment-invitations", only: [:show]
    resources :group_assignment_repos,       path: "group-assignment-repos",       only: %i[show destroy]
    resources :group_assignments,            path: "group-assignments",            only: [:show]

    resources :groupings, only: [:show]
    resources :groups,    only: [:show]
  end
end

app/controllers/organizations_controller.rb
# frozen_string_literal: true

class OrganizationsController < Orgs::Controller
  before_action :ensure_team_management_flipper_is_enabled, only: [:show_groupings]

  before_action :authorize_organization_addition,     only: [:create]
  before_action :set_users_github_organizations,      only: %i[index new create]
  before_action :add_current_user_to_organizations,   only: [:index]
  before_action :paginate_users_github_organizations, only: %i[new create]
  before_action :verify_user_belongs_to_organization, only: [:remove_user]

  skip_before_action :ensure_current_organization,                         only: %i[index new create]
  skip_before_action :ensure_current_organization_visible_to_current_user, only: %i[index new create]

  def index
    @organizations = current_user.organizations.page(params[:page])
  end

  def new
    @organization = Organization.new
  end

  # rubocop:disable MethodLength
  def create
    result = Organization::Creator.perform(
      github_id: new_organization_params[:github_id],
      users: new_organization_params[:users]
    )

    if result.success?
      @organization = result.organization
      redirect_to setup_organization_path(@organization)
    else
      flash[:error] = result.error
      redirect_to new_organization_path
    end
  end
  # rubocop:enable MethodLength

  def show
    # sort assignments by title
    @assignments = Kaminari
                   .paginate_array(current_organization.all_assignments(with_invitations: true)
                   .sort_by(&:title))
                   .page(params[:page])
  end

  def edit; end

  def invitation; end

  def show_groupings
    @groupings = current_organization.groupings
  end

  def update
    if current_organization.update_attributes(update_organization_params)
      flash[:success] = "Organization \"#{current_organization.title}\" updated"
      redirect_to current_organization
    else
      render :edit
    end
  end

  def destroy
    if current_organization.update_attributes(deleted_at: Time.zone.now)
      DestroyResourceJob.perform_later(current_organization)

      flash[:success] = "Your organization, @#{current_organization.github_organization.login} is being reset"
      redirect_to organizations_path
    else
      render :edit
    end
  end

  def remove_user
    if current_organization.one_owner_remains?
      flash[:error] = "The user can not be removed from the classroom"
    else
      transfer_assignments if @removed_user.owns_all_assignments_for?(current_organization)
      current_organization.users.delete(@removed_user)
      flash[:success] = "The user has been removed from the classroom"
    end

    redirect_to settings_invitations_organization_path
  end

  def new_assignment; end

  def invite; end

  def setup; end

  def setup_organization
    if current_organization.update_attributes(update_organization_params)
      redirect_to invite_organization_path(current_organization)
    else
      render :setup
    end
  end

  private

  def authorize_organization_addition
    new_github_organization = github_organization_from_params

    return if new_github_organization.admin?(current_user.github_user.login)
    raise NotAuthorized, "You are not permitted to add this organization as a classroom"
  end

  def github_organization_from_params
    @github_organization_from_params ||= GitHubOrganization.new(current_user.github_client,
                                                                params[:organization][:github_id].to_i)
  end

  def new_organization_params
    params.require(:organization).permit(:github_id).merge(users: [current_user])
  end

  # rubocop:disable AbcSize
  def set_users_github_organizations
    @users_github_organizations = current_user.github_user.organization_memberships.map do |membership|
      {
        classroom:   Organization.unscoped.find_by(github_id: membership.organization.id),
        github_id:   membership.organization.id,
        login:       membership.organization.login,
        owner_login: membership.user.login,
        role:        membership.role
      }
    end
  end
  # rubocop:enable AbcSize

  # Check if the current user has any organizations with admin privilege,
  # if so add the user to the corresponding classroom automatically.
  def add_current_user_to_organizations
    @users_github_organizations.each do |organization|
      classroom = organization[:classroom]
      if classroom.present? && !classroom.users.include?(current_user)
        create_user_organization_access(classroom)
      end
    end
  end

  def create_user_organization_access(organization)
    github_org = GitHubOrganization.new(current_user.github_client, organization.github_id)
    return unless github_org.admin?(current_user.github_user.login)
    organization.users << current_user
  end

  def paginate_users_github_organizations
    @users_github_organizations = Kaminari.paginate_array(@users_github_organizations).page(params[:page]).per(24)
  end

  def update_organization_params
    params
      .require(:organization)
      .permit(:title)
  end

  def verify_user_belongs_to_organization
    @removed_user = User.find(params[:user_id])
    not_found unless current_organization.users.map(&:id).include?(@removed_user.id)
  end

  def transfer_assignments
    new_owner = current_organization.users.where.not(id: @removed_user.id).first
    current_organization.all_assignments.map do |assignment|
      next unless assignment.creator_id == @removed_user.id
      assignment.update_attributes(creator_id: new_owner.id)
    end
  end
end

app/controllers/stafftools/assignment_invitations_controller.rb
# frozen_string_literal: true

module Stafftools
  class AssignmentInvitationsController < StafftoolsController
    before_action :set_assignment_invitation

    def show; end

    private

    def set_assignment_invitation
      @assignment_invitation = AssignmentInvitation.find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools/assignment_repos_controller.rb
# frozen_string_literal: true

module Stafftools
  class AssignmentReposController < StafftoolsController
    before_action :set_assignment_repo

    def show; end

    def destroy
      assignment = @assignment_repo.assignment

      if @assignment_repo.destroy
        flash[:success] = "Assignment repository was destroyed"
        redirect_to stafftools_assignment_path(assignment.id)
      else
        flash[:error] = "Could not delete assignment repository"
        render :show
      end
    end

    private

    def set_assignment_repo
      @assignment_repo = AssignmentRepo.find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools/assignments_controller.rb
# frozen_string_literal: true

module Stafftools
  class AssignmentsController < StafftoolsController
    before_action :set_assignment

    def show; end

    private

    def set_assignment
      @assignment = Assignment.find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools/deadlines_controller.rb
# frozen_string_literal: true

module Stafftools
  class DeadlinesController < StafftoolsController
    before_action :set_deadline

    def show; end

    private

    def set_deadline
      @deadline = Deadline.find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools/group_assignment_invitations_controller.rb
# frozen_string_literal: true

module Stafftools
  class GroupAssignmentInvitationsController < StafftoolsController
    before_action :set_group_assignment_invitation

    def show; end

    private

    def set_group_assignment_invitation
      @group_assignment_invitation = GroupAssignmentInvitation.find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools/group_assignment_repos_controller.rb
# frozen_string_literal: true

module Stafftools
  class GroupAssignmentReposController < StafftoolsController
    before_action :set_group_assignment_repo

    def show; end

    def destroy
      group_assignment = @group_assignment_repo.group_assignment

      if @group_assignment_repo.destroy
        flash[:success] = "Group assignment repository was destroyed"
        redirect_to stafftools_group_assignment_path(group_assignment.id)
      else
        flash[:error] = "Could not delete group assignment repository"
        render :show
      end
    end

    private

    def set_group_assignment_repo
      @group_assignment_repo = GroupAssignmentRepo.find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools/group_assignments_controller.rb
# frozen_string_literal: true

module Stafftools
  class GroupAssignmentsController < StafftoolsController
    before_action :set_group_assignment

    def show; end

    private

    def set_group_assignment
      @group_assignment = GroupAssignment.find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools/groupings_controller.rb
# frozen_string_literal: true

module Stafftools
  class GroupingsController < StafftoolsController
    before_action :set_grouping

    def show; end

    private

    def set_grouping
      @grouping = Grouping.find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools/groups_controller.rb
# frozen_string_literal: true

module Stafftools
  class GroupsController < StafftoolsController
    before_action :set_group

    def show; end

    private

    def set_group
      @group = Group.find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools/organizations_controller.rb
# frozen_string_literal: true

module Stafftools
  class OrganizationsController < StafftoolsController
    before_action :set_organization

    def show; end

    def remove_user
      user = User.find(params[:user_id])

      if Assignment.find_by(creator: user).present?
        flash[:error] = "This user owns at least one assignment and cannot be deleted"
      else
        @organization.users.delete(user)
        flash[:success] = "The user has been removed from the classroom"
      end

      redirect_to stafftools_organization_path(@organization.id)
    end

    private

    def set_organization
      @organization = Organization.includes(:users).find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools/repo_accesses_controller.rb
# frozen_string_literal: true

module Stafftools
  class RepoAccessesController < StafftoolsController
    before_action :set_repo_access

    def show; end

    private

    def set_repo_access
      @repo_access = RepoAccess.find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools/resources_controller.rb
# frozen_string_literal: true

module Stafftools
  class ResourcesController < StafftoolsController
    before_action :set_resources

    def index; end

    def search
      respond_to do |format|
        format.html { render partial: "stafftools/resources/search_results", locals: { resources: @resources } }
      end
    end

    private

    def set_resources
      return @resources = nil if params[:query].blank?
      @resources = StafftoolsIndex
                   .query(match_phrase_prefix(params[:query]))
                   .order(_type: :asc)
                   .page(params[:page])
                   .per(20)
    end

    def match_phrase_prefix(query)
      searchable_fields = %w[github_id github_repo_id github_team_id id key login name slug title uid]
      { bool: { should: searchable_fields.map { |field| { "match_phrase_prefix" => { field => query } } } } }
    end
  end
end

app/controllers/stafftools/users_controller.rb
# frozen_string_literal: true

module Stafftools
  class UsersController < StafftoolsController
    skip_before_action :authorize_access, only: [:stop_impersonating]

    before_action :set_user, except: [:stop_impersonating]

    def show; end

    def impersonate
      session[:impersonated_user_id] = @user.id
      redirect_to root_path
    end

    def stop_impersonating
      not_found unless true_user.try(:staff?)

      session.delete(:impersonated_user_id)
      redirect_to stafftools_root_path
    end

    private

    def set_user
      @user = User.find_by!(id: params[:id])
    end
  end
end

app/controllers/stafftools_controller.rb
# frozen_string_literal: true

class StafftoolsController < ApplicationController
  layout "stafftools"

  before_action :authorize_access

  private

  def authorize_access
    not_found unless current_user.try(:staff?)
  end
end

app/views/stafftools/organizations/_assignment.html.erb
<li class="clearfix">
  <%= octicon 'person' %>
  <strong><%= link_to assignment.title, stafftools_assignment_path(assignment.id) %></strong>
</li>

app/views/stafftools/organizations/_group_assignment.html.erb
<li class="clearfix">
  <%= octicon 'organization' %>
  <strong><%= link_to group_assignment.title, stafftools_group_assignment_path(group_assignment.id) %></strong>
</li>

app/views/stafftools/organizations/_grouping.html.erb
<li class="clearfix">
  <%= octicon 'organization' %>
  <strong><%= link_to grouping.title, stafftools_grouping_path(grouping.id) %></strong>
</li>

app/views/stafftools/organizations/_organization.html.erb
<div class="d-flex flex-md-row flex-items-center classroom-resource-item">
  <div class="col-1 d-flexp">
    <%= image_tag github_avatar_url(organization.github_id, 96), height: 48, width: 48, class: 'avatar left', alt: "@#{organization.login}" %>
  </div>

  <div class="col-10 col-md-10 d-flex flex-column">
    <%= link_to stafftools_organization_path(organization.id) do %>
      <strong class="search-result-title"><%= organization.login %></strong>
    <% end %>

    <span class="text-gray css-truncate css-truncate-target"><%= t('views.stafftools.organizations.added') %> <%= local_time_ago(organization.created_at) %></span><br>
  </div>
</div>

app/views/stafftools/organizations/_remove_user_from_organization_modal.html.erb
<div class="remodal text-left" data-remodal-id="remove-user-from-organization-<%= user.id %>">
  <button data-remodal-action="close" class="remodal-close"><%= octicon 'x' %></button>
  <h2 class="remodal-header"><%= t('views.stafftools.organizations.remove_owner_header') %></h2>

  <div class="remodal-description">
    <p><%= t('views.stafftools.organizations.remove_owner_desc') %></p>
  </div>

  <%= button_to t('views.stafftools.organizations.remove_user_btn_text'), remove_user_stafftools_organization_path(@organization.id, user.id), method: :delete, class: 'btn btn-danger btn-block js-submit' %>
</div>

app/views/stafftools/organizations/_user.html.erb
<%= image_tag user.github_user.github_avatar_url(40), height: 20, width: 20, alt: "@#{user.github_user.login}" %>
<strong><%= link_to user.github_user.login, stafftools_user_path(user.id) %></strong>

app/views/stafftools/organizations/show.html.erb
<div class="site-content">
  <div class="d-flex flex-md-row flex-items-center stafftools-page-header">
    <div class="col-1 assignment-icon assignment-icon-group">
      <%= image_tag @organization.github_organization.github_avatar_url(96), height: 48, width: 48, class: 'avatar left', alt: "@#{@organization.github_organization.login}" %>
    </div>

    <div class="col-10 col-md-10 d-flex flex-column">
      <h2 class="stafftools-heading">
        <%= @organization.title %>
      </h2>

      <p class="assignment-type text-gray"><%= t('views.stafftools.organizations.classroom') %></p>
    </div>
  </div>

  <div class="boxed-group">
    <h3><%= t('views.stafftools.organizations.classroom') %></h3>

    <div class="boxed-group-inner">
      <table>
        <tr>
          <td class="text-emphasized"><%= t('views.stafftools.organizations.id') %></td>
          <td><%= @organization.id %></td>
        </tr>
        <tr>
          <td class="text-emphasized"><%= t('views.stafftools.organizations.classroom') %></td>
          <td><%= link_to organization_url(@organization), organization_url(@organization) %></td>
        </tr>
        <tr>
          <td class="text-emphasized"><%= t('views.stafftools.organizations.joined_on') %></td>
          <td><%= local_time(@organization.created_at) %></td>
        </tr>
        <tr>
          <td class="text-emphasized"><%= t('views.stafftools.organizations.last_updated') %></td>
          <td><%= local_time(@organization.updated_at) %></td>
        </tr>
      </table>
    </div>
  </div>

  <div class="boxed-group">
    <h3><%= t('views.stafftools.organizations.github_organization') %></h3>

    <div class="boxed-group-inner">
      <table>
        <tr>
          <td class="text-emphasized"><%= t('views.stafftools.organizations.id') %></td>
          <td><%= @organization.github_id %></td>
        </tr>
        <tr>
          <td class="text-emphasized"><%= t('views.stafftools.organizations.homepage') %></td>
          <td><%= link_to @organization.github_organization.html_url, @organization.github_organization.html_url %></td>
        </tr>
        <% if @organization.webhook_id.present? %>
          <tr>
            <td class="text-emphasized"><%= t('views.stafftools.organizations.webhook_url') %></td>
            <% url = "https://github.com/organizations/#{@organization.github_organization.login}/settings/hooks/#{@organization.webhook_id}" %>
            <td><%= link_to url, url %></td>
          </tr>
          <tr>
            <td class="text-emphasized"><%= t('views.stafftools.organizations.webhook_enabled_check') %></td>
            <td><%= @organization.is_webhook_active? %></td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>

  <div class="boxed-group">
    <h3><%= t('views.stafftools.organizations.owners') %></h3>

    <div class="boxed-group-inner">
      <ul class="boxed-group-list standalone">
        <% @organization.users.each do |user| %>
          <li class="stafftools-button-li clearfix">
            <%= render partial: 'stafftools/organizations/user', locals: { user: user } %>
            <a data-remodal-target="remove-user-from-organization-<%= user.id %>" class="btn btn-danger stafftools-small-button<%= ' disabled' if @organization.users.count < 2 %>">Remove</a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <% @organization.users.each do |user| %>
    <%= render partial: 'stafftools/organizations/remove_user_from_organization_modal', locals: { user: user } %>
  <% end %>

  <% if @organization.all_assignments.present? %>
    <div class="boxed-group">
      <h3><%= t('views.stafftools.organizations.assignments') %></h3>

      <div class="boxed-group-inner">
        <ul class="boxed-group-list standalone">
          <% @organization.all_assignments.each do |assignment| %>
            <% type = assignment.class.to_s.underscore %>
            <%= render partial: "stafftools/organizations/#{type}", locals: { :"#{type}" => assignment } %>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <% if @organization.groupings.present? %>
    <div class="boxed-group">
      <h3><%= t('views.stafftools.organizations.groupings') %></h3>

      <div class="boxed-group-inner">
        <ul class="boxed-group-list standalone">
          <%= render partial: "stafftools/organizations/grouping", collection: @organization.groupings %>
        </ul>
      </div>
    </div>
  <% end %>
</div>